sudo: required

language: java

services:
  - docker

before_install:
  - mvn package
  - docker build -t cestore/ce-store .

script:
  - docker run -d cestore/ce-store
  - docker ps | grep ce-store

after_success:
  - docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push cestore/ce-store
